### ISSUE TITLE
Address Doctype

### ISSUE THREAD

**Issue by Basawa-SELCO** [Basawa-SELCO/selco_v2#10]
Address Title should automatically be picked up. (While adding address to some particular customer)

If the SELCO Customer link feild is selected then the address title and address is getting saved. So the SELCO Customer link feild should be automatically set.

**Comment by gaurav-naik** [comment]
- [x] Remove SELCO Customer link field
- [x] Check dynamic link table while creating customers
- [ ] Check intermittent error while populating dynamic link during new address

**Comment by Basawa-SELCO** [comment]
We have hidden the 'Address Title' field.

SELCO Customer link should automatically be picked up. Otherwise it throws 'Address Title Field is Mandatory'

**Comment by gaurav-naik** [comment]
SELCO Custmer Link is deprecated. I will remove that field. Customer will get linked to address automatically.

**Comment by Basawa-SELCO** [comment]
Check intermittent error while populating dynamic link during new address.
The linking is not happening. So the Address Title is required, which we thought will be hidden.

**Comment by Basawa-SELCO** [comment]
not fixed

**Comment by umairsy** [comment]
Please update the last issue by Customer/Supplier not updating in the Address on support@erpnext.com

**Comment by gaurav-naik** [comment]
Address fixes for both Warehouse and Customer have been implmented and merged on the hotfix branch. I will update here once they are merged into the core branch, following which I will also update the servers.

**Comment by gaurav-naik** [comment]
New Address feature is now working correctly for both Customers and Warehouses on the test server. Kindly confirm if it is working on the production server.
