### ISSUE TITLE
Add Row in Issue Child Table doesnt work consistently

### ISSUE THREAD

**Issue by Basawa-SELCO** [Basawa-SELCO/selco_v2#102]
In Issue Doctype, the Add Row button does come consistently for the Service Records Details child table.
Sometimes it comes back on refresh and sometimes it goes off on refresh. Not sure if the issue is because the child table code is in Custom script and depends on the speed of execution of the code. But its very inconsistent and affecting the work especially looks like on a slower internet.

![image](https://user-images.githubusercontent.com/24898695/41830104-7496f504-785c-11e8-9c0e-d4a29f17b171.png)

**Comment by gaurav-naik** [comment]
Grid becomes readonly for Shimoga Service Center (shimoga_service_center@selco-india.com)
Behaviour consistent with permission restrictions.

**Comment by Basawa-SELCO** [comment]
Fix to be included in Ver 11
