### ISSUE TITLE
selco_customizations.py

### ISSUE THREAD

**Issue by Basawa-SELCO** [Basawa-SELCO/selco_v2#117]
Customer validation based on Contact Number not working

if not ( doc.selco_customer_contact_number or doc.selco_landline_mobile_2 ):
        frappe.throw("Enter either Customer Contact Number ( Mobile 1 ) or Mobile 2 / Landline") 

Similar validation in Lead is working

if not ( doc.selco_customer_contact_number__mobile_1 or doc.selco_customer_contact_number__mobile_2_landline ):
        frappe.throw("Enter either Customer Contact Number ( Mobile 1 ) or Mobile 2 / Landline")

**Comment by gaurav-naik** [comment]
A fix has been pushed for this.

**Comment by Basawa-SELCO** [comment]
Fixed
