### ISSUE TITLE
Payment Entry DocType

### ISSUE THREAD

**Issue by Basawa-SELCO** [Basawa-SELCO/selco_v2#13]
In Suppliers Payment (Payment Entry) the fileds related to Customer Payment Should not get displayed Ex: Money Received By, Financed By Bank/Microfinance/NGO ? ,O.A.No, O.A. Date

**Comment by gaurav-naik** [comment]
- [x] Investigate Payment made against Purchase Invoice.

**Comment by gaurav-naik** [comment]
This is currently not happening in v7. Feature added: When type == Pay, hide fields.

**Comment by Basawa-SELCO** [comment]
In Payment Entry (Customer) if Money Recieved By == 'cash' , It should not ask for 'Cheque/UTR/Reference No','Cheque/Reference Date','Cheque Issuing Bank'.

'Account Paid To'   field should automatically be picked up.

'Account Paid From' field should automatically be picked up


In Payment Entry (Customer) if Money Recieved By == 'Cheque/DD', It should ask for 'Cheque/UTR/Reference No','Cheque/Reference Date','Cheque Issuing Bank'.


In Payment Entry (Customer) if Party Type == customer, Paid Amount field should not get displayed amd Recieved Amount field should get displayed.

**Comment by gaurav-naik** [comment]
Observations:
1. Mode of payment set to Cash correctly but Reference No is still mandatory
2. Cheque/UTR/Reference field is not visible when mode of payment is not Cash
3. Paid_to field is set correctly, but not visible.


- [x] Check custom field visibility conditions

**Comment by gaurav-naik** [comment]
> In Payment Entry (Customer) if Money Recieved By == 'cash' , It should not ask for 'Cheque/UTR/Reference No','Cheque/Reference Date','Cheque Issuing Bank'.

> 'Account Paid To' field should automatically be picked up.

This field will get set correctly provided the right account is set in Branch.

> 'Account Paid From' field should automatically be picked up

Fixed the condition that prevented this field from showing. Picks up the party's account as a default feature.

> In Payment Entry (Customer) if Money Recieved By == 'Cheque/DD', It should ask for 'Cheque/UTR/Reference No','Cheque/Reference Date','Cheque Issuing Bank'.

Fixed

**Comment by gaurav-naik** [comment]
- [x] Hide Create New Customer and Address buttons.
