### ISSUE TITLE
Service Call

### ISSUE THREAD

**Issue by Basawa-SELCO** [Basawa-SELCO/selco_v2#14]
Submit Option is getting displayed in Service Call

**Comment by gaurav-naik** [comment]
Service Call has a Submit button in version 7. Kindly confirm if it is to be removed in the new version.

**Comment by Basawa-SELCO** [comment]
Sorry, Wrong description. what we meant is : Submit Option is **not** getting displayed in Service Call

**Comment by gaurav-naik** [comment]
Permissions issue. Can test again once appropriate roles are set.

**Comment by gaurav-naik** [comment]
Closing this issue.
