### ISSUE TITLE
Material Request DocType

### ISSUE THREAD

**Issue by Basawa-SELCO** [Basawa-SELCO/selco_v2#15]
Logistics Manager Remarks field is not displayed before saving the form.

Godown OA remarks, Senior manager remarks, Logistics Manage Remarks, DC No, DC Date - fields are not in Open State aftersaving material request.

Workflow is not displayed.

Get Item buttons are displayed multiple times:

![get_items_from_bom_in_ibm](https://user-images.githubusercontent.com/24898695/39417581-e2bb54dc-4c72-11e8-9c4a-38d382aac99b.png)

**Comment by gaurav-naik** [comment]
Added Logistics Manager Remarks field with appropriate perm levels. (Not updated on test server)

- [x] Get Items from BOM SELCO button should appear only once
- [ ] Get Items from BOM original should be hidden.

**Comment by Basawa-SELCO** [comment]
UOM Conversion Factor has to be set automatically in Material Request line Item , When Items are pulled from Get Items From BOM

Get Items From BOM original is still getting displayed

**Comment by gaurav-naik** [comment]
- [x] Set UOM Conversion Factor in MR line items if found in results of get_items_from_bom1

**Comment by Basawa-SELCO** [comment]
> `Added Logistics Manager Remarks field with appropriate perm levels. (Not updated on test server)

Please let us know if this has been done. Its not working.
So we have added following lines in Material Request-Client Custom Script


> frm.set_df_property("selco_logistics_manager_comments", "read_only",0);
> frm.set_df_property("selco_senior_manager_comments", "read_only",0);



`

**Comment by gaurav-naik** [comment]
Logistics Manager comments were appearing correctly. Kindly confirm this, so the issue can be closed.

**Comment by Basawa-SELCO** [comment]
Get Items from BOM original should be hidden.
