### ISSUE TITLE
Warranty Claim DocType

### ISSUE THREAD

**Issue by Basawa-SELCO** [Basawa-SELCO/selco_v2#17]
Details of the document Section should automatically be picked from issue. For Ex: ICS Number

Details of the Document, Courier Details,  Branch To Godown DC Details -> These sections, Remarks By Godown -> field  should appear when warranty claim is in 'Warranty Claim Format Raised - WC' State, 'Warranty Claim Format Approved - WC','Dispatch Pending From Godown','Dispatched From Godown' State.

Item Codes, Supplier Name related to selected Item Group should get displayed (check box). For Ex: If you select 'Battery' as Item Group, Item codes related to Battery Item Group should get displayed. Similarly Supplier of type Battery Manufacturer should get displayed.

**Comment by gaurav-naik** [comment]
>Details of the document Section should automatically be picked from issue. For Ex: ICS Number

Does this happen on saving the Warranty Claim? I do not see this info being pulled automatically on the production server.

> Details of the Document, Courier Details, Branch To Godown DC Details -> These sections, Remarks By Godown -> field should appear when warranty claim is in 'Warranty Claim Format Raised - WC' State, 'Warranty Claim Format Approved - WC','Dispatch Pending From Godown','Dispatched From Godown' State.

These are currently appearing in the Draft state on the production server

>Item Codes, Supplier Name related to selected Item Group should get displayed (check box). For Ex: If you select 'Battery' as Item Group, Item codes related to Battery Item Group should get displayed. Similarly Supplier of type Battery Manufacturer should get displayed.

Working as expected after adding the correct supplier type and item group : http://159.89.165.44:8001/desk#Form/Warranty%20Claim/CI-00004

**Comment by gaurav-naik** [comment]
>Details of the Document, Courier Details, Branch To Godown DC Details -> These sections, Remarks By Godown -> field should appear when warranty claim is in 'Warranty Claim Format Raised - WC' State, 'Warranty Claim Format Approved - WC','Dispatch Pending From Godown','Dispatched From Godown' State.

- [x] Pull details from Issue into Warranty Claim
- [x] Remarks By Godown should be visible after submission (Line 165, Custom Script)
