### ISSUE TITLE
Service Person and Financing Institution (Added custom fields, custom script)

### ISSUE THREAD

**Issue by Basawa-SELCO** [Basawa-SELCO/selco_v2#22]
Added Custom field - 'Disabled'

In Custom Script  added following script

frappe.ui.form.on("Issue", "refresh",
    function(frm) {

cur_frm.set_query("service_person", "service_record_details", function(doc, cdt, cdn) {
	var d = locals[cdt][cdn];
	return{
		filters: [
			['Service Person', 'do_not_show_in_issue', 'in', '0'],
		]
	}
});

})

Edited Custom Field ' Service or Installation'

In Payment Entry, Added depends on for field 'Financing Institution Details'

**Comment by Basawa-SELCO** [comment]
Please ensure that these changes are not overwritten by any future code push.

**Comment by gaurav-naik** [comment]
### Note

If a doctype does not belong to any of ERPNext's or Frappe's default modules (e.g. Service Person, a custom doctype under the SELCO module), then its fields can be edited directly. No need to use customize form for such doctypes.

### Fixes

> Added Custom field - 'Disabled'

Added Disabled check field to Service Person directly.

> In Custom Script added following script...

Included updates in Issue custom script.

> Edited Custom Field ' Service or Installation'

Added blank option in service_or_installation field on Service Person

>In Payment Entry, Added depends on for field 'Financing Institution Details'

Depends on already existed on this field:
```eval:(doc.paid_from && doc.paid_to && doc.paid_amount && doc.received_amount)```
