### ISSUE TITLE
BOM  ( Stock Entry)

### ISSUE THREAD

**Issue by Basawa-SELCO** [Basawa-SELCO/selco_v2#23]
While Cancelling Stock Entry (Entry Type == BOM), It throws following error.
![bom_cancel](https://user-images.githubusercontent.com/24898695/39865923-340ab14c-546c-11e8-8210-d9b721d91933.png)

**Comment by gaurav-naik** [comment]
Fixed. Kindly verify.

**Comment by gaurav-naik** [comment]
Closing this issue as this problem has not recurred.
