### ISSUE TITLE
Server is crashing

### ISSUE THREAD

**Issue by Basawa-SELCO** [Basawa-SELCO/selco_v2#26]
Not sure what is happening here.
Try adding new Address to a Warehouse (New Address Button). Its not saving and after sometime the server becomes un reachable, may be its crashing. This is serious issue and needs to checked on priority.

**Comment by gaurav-naik** [comment]
Checking now.

**Comment by gaurav-naik** [comment]
Was able to save an address on the test warehouse without an problem. Could you share more details? Maybe the specific warehouse for which this issue occurred? I am trying to replicate it at my end as well.

**Comment by Basawa-SELCO** [comment]
Go to Warehouse Tree -> Karnataka Warehouses->Manipal GOD->Manipal Godown
Click on the New address button. Type of address "Billing
Save it. The save works and the address is created. But it doesnt showup in the Parent Manipal Godown page.
The Server becomes inaccessible after saving.

**Comment by Basawa-SELCO** [comment]
- The Server Crash problem can be ignored.
- But the Address problem is still there. Its a link problem. When we try to add an Address in the Warehouse page, the Address gets saved but its not linked to the Warehouse and hence it doesnot display. They we have to manually do the linking. After that it appears in the Address of the Warehouse

**Comment by umairsy** [comment]
If server crashing is no more an issue, then this issue could be closed. For address, I believe we are communicating through other channels?

**Comment by gaurav-naik** [comment]
I have updated issue #10. We were communicating over the same email thread previously.

**Comment by gaurav-naik** [comment]
Shall I close this issue now?

**Comment by Basawa-SELCO** [comment]
Closed. Looks like a Firewall issue, fixed by Frappe team
