### ISSUE TITLE
Journal Entry

### ISSUE THREAD

**Issue by Basawa-SELCO** [Basawa-SELCO/selco_v2#27]
I have  added following options in Journal Entry  "Entry Type"
Bank Payment
Cash Payment
Debit Note
Credit Note
Contra Entry
Receipt
Commission Journal
Write Off Entry
Opening Entry
Opening Entry - HO - SELCO
Journal Entry - HO - FD
Payment Entry - HO - SBI

**Comment by Basawa-SELCO** [comment]
Gaurav - hope this is fine to add these options. We can close this issue in Github?

**Comment by Basawa-SELCO** [comment]
The entries are gone from the list. PLease add it back.

**Comment by Basawa-SELCO** [comment]
These 2 are not required. We will use the default option of ERP.
Bank Payment
Cash Payment

**Comment by Basawa-SELCO** [comment]
Opening Entry - HO - SELCO
Journal Entry - HO - FD
Payment Entry - HO - SBI

**Comment by gaurav-naik** [comment]
These options are present in my update but they did not get applied. I have added them in.
I have also edited the custom scripts to use the default Bank Entry and Cash Entry options.

**Comment by Basawa-SELCO** [comment]
Fixed now.

**Comment by Basawa-SELCO** [comment]
Again got overwritten..this is serious.. please ensure that code is not overwritten for anything like this.

**Comment by Basawa-SELCO** [comment]
Fixed
