### ISSUE TITLE
Stock Entry (Material Inward) Godown to Branch

### ISSUE THREAD

**Issue by Basawa-SELCO** [Basawa-SELCO/selco_v2#31]
![dc_error](https://user-images.githubusercontent.com/24898695/40406722-74b331c0-5e7f-11e8-811e-ea5e04cc0fd9.png)

**Comment by Basawa-SELCO** [comment]
The case is - Outward DC from Godown to Branch; Branch trying to take inward through a GRN Stock entry and we are getting this error

**Comment by Basawa-SELCO** [comment]
bench/apps/selco/selco/selco/selco_customizations.py", line 671, in selco_stock_entry_on_submit_updates
    frappe.throw("Please enter correct Quantity")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 323, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 309, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 282, in _raise_exception
    raise raise_exception(encode(msg))
ValidationError: Please enter correct Quantity

**Comment by gaurav-naik** [comment]
This appears to be a thrown via a custom validation. Would be better to have more clarity on the feature  before implementing a fix.

**Comment by Basawa-SELCO** [comment]
The issue is back again. This feature was done by Basawaraj; Poorvi and I dont have much idea about it. 
So we analysed the code in the App and this is our understanding and probable fix. Can you please check and fix?

The feature is about Repair stock. The flow is - Rejection In from Customer to Branch->Outward DC from Branch to Warehouse->GRN at Warehouse->Rejection Out from Warehouse to Supplier -> **Rejection In from Supplier to Warehouse** ->Outward DC from Warehouse to Branch -> **GRN at Branch** -> **Rejection Out from Branch to Customer.**

There is code to check (pasted below) if the number of items is proper for the Rejection Item quantity for the flow marked in Bold.

**We think the issue is that there is no check for the Type of Material.** The entire cycle should only work for Repair Stock and not for Good Stock.


@frappe.whitelist()
def selco_stock_entry_on_submit_updates(doc,method):
    if((doc.type_of_stock_entry == "Rejection Out") and (doc.supplier_or_customer == "Customer")):
        for item in doc.items:
            ref_doc = frappe.get_doc("Stock Entry",item.reference_rej_in_or_rej_ot)
            #frappe.msgprint(ref_doc)
            for ref_item in ref_doc.items:
                if ref_item.item_code == item.item_code:
                    ref_item.reference_rej_in_or_rej_quantity = ref_item.reference_rej_in_or_rej_quantity + item.qty
                    if ref_item.reference_rej_in_or_rej_quantity > ref_item.qty:
                        frappe.throw("Please enter correct Quantity")
            ref_doc.save()
    if((doc.type_of_stock_entry == "Rejection In") and (doc.supplier_or_customer == "Supplier")):
        for item in doc.items:
            ref_doc = frappe.get_doc("Stock Entry",item.reference_rej_in_or_rej_ot)
            #frappe.msgprint(ref_doc)
            for ref_item in ref_doc.items:
                if ref_item.item_code == item.item_code:
                    ref_item.reference_rej_in_or_rej_quantity = ref_item.reference_rej_in_or_rej_quantity + item.qty
                    if ref_item.reference_rej_in_or_rej_quantity > ref_item.qty:
                        frappe.throw("Please enter correct Quantity")
            ref_doc.save(ignore_permissions=True)
    if(doc.type_of_stock_entry == "GRN"):
        for item in doc.items:
            item.reference_rej_in_or_rej_ot = doc.suppliers_ref
            ref_doc = frappe.get_doc("Stock Entry",doc.suppliers_ref)
            #frappe.msgprint(ref_doc)
            for ref_item in ref_doc.items:
                if (ref_item.item_code == item.item_code and ref_item.item_code == item.item_code):
                    ref_item.reference_rej_in_or_rej_quantity = ref_item.reference_rej_in_or_rej_quantity + item.qty
                    if ref_item.reference_rej_in_or_rej_quantity > ref_item.qty:
                        frappe.throw("Please enter correct Quantity")
            ref_doc.save(ignore_permissions=True)
    if(doc.type_of_stock_entry == "Outward DC"):
        pass

**Comment by Basawa-SELCO** [comment]
Any update on this?

**Comment by gaurav-naik** [comment]
Added material type check when stock entry type is GRN.
Updating server now.

**Comment by gaurav-naik** [comment]
Kindly verify if this has been fixed.
