### ISSUE TITLE
Workflow issues

### ISSUE THREAD

**Issue by Basawa-SELCO** [Basawa-SELCO/selco_v2#4]
Workflow is defined but all the states and rules are not there. 
In Issue DocType Action button is not coming to select the correct workflow

**Comment by gaurav-naik** [comment]
Values under the "Allowed" column for some Workflow states has changed from SELCO Service Basic to SELCO Branch Office Administrator. Please confirm if I should set them as they were in v7

### v10
![complaint_management_workflow_states](https://user-images.githubusercontent.com/17795124/39405045-16dd7424-4bbb-11e8-8b78-2e0bfb714036.png)
### v7
![complaint_management_workflow_states_v7](https://user-images.githubusercontent.com/17795124/39405046-1b9493e4-4bbb-11e8-93c4-86f364027986.png)

**Comment by Basawa-SELCO** [comment]
Yes Please set it as v7

**Comment by gaurav-naik** [comment]
- [x] Ensure that Warranty Claim and IBM workflows in v10 are in sync with those in v7
