### ISSUE TITLE
Journal Entry Naming Series

### ISSUE THREAD

**Issue by Basawa-SELCO** [Basawa-SELCO/selco_v2#48]
When entry type is Opening Entry, then it is taking naming series as REC/

**Comment by gaurav-naik** [comment]
This line:
```cur_frm.add_fetch("selco_branch", "selco_receipt_naming_series", "naming_series"); ```

has been replaced with:
```cur_frm.add_fetch("selco_branch", "selco_journal_entry_naming_series", "naming_series"); ```
