### ISSUE TITLE
.js and selco_customizations.py

### ISSUE THREAD

**Issue by Basawa-SELCO** [Basawa-SELCO/selco_v2#49]
Please replace year  /16-17/  to /18-19/

**Comment by Basawa-SELCO** [comment]
Journal Entry JS still has 17-18. 

And also, Opening Entry is taking 17-18 ( probably from the PY side).

Please update this asap.

**Comment by Basawa-SELCO** [comment]
Journal Entry JS still has 17-18.

And also, Opening Entry is taking 17-18 ( probably from the PY side).

Please update this asap.

**Comment by gaurav-naik** [comment]
Custom script has been updated. Nothing on the server side which overrides year for Journal Entry.
