### ISSUE TITLE
Purchase Order and Warehouse

### ISSUE THREAD

**Issue by Basawa-SELCO** [Basawa-SELCO/selco_v2#5]
In Warehouse Tree, Some custom feilds are missing. Ex: SELCO State GSTIN,Linked - Address field.

In Purchase Order ,Tried to select Godown ->Godown address link and Godown address details are not getting displayed.

In  Purchase Order, Supplier's GSTIN field , Terms and  Conditions should automatically be picked up.

**Comment by gaurav-naik** [comment]
> In Warehouse Tree, Some custom feilds are missing. Ex: SELCO State GSTIN,Linked - Address field.

Fields added.

> In Purchase Order ,Tried to select Godown ->Godown address link and Godown address details are not getting displayed.

Addresses should be linked to Warehouses using the "New Address" button. 
While creating a new Address, please ensure that you set the Link Doctype to "Warehouse" and Link Name to the desired warehouse.
Try selecting "Bangalore GOD - SELCO" in a purchase order - its details will load correctly.

> In Purchase Order, Supplier's GSTIN field , Terms and Conditions should automatically be picked up.

Fixed. Please verify.

**Comment by Basawa-SELCO** [comment]
In Warehouse a custom field 'Warehouse Type' should be added.

**Comment by gaurav-naik** [comment]
Which ID are you using to log in?

![warehouse_type](https://user-images.githubusercontent.com/17795124/39417813-6394b548-4c74-11e8-86a4-781cf53df4cc.png)

**Comment by gaurav-naik** [comment]
- [x] Add Warehouse Type Link field on Warehouse
