### ISSUE TITLE
Upload Signature in Print Format

### ISSUE THREAD

**Issue by Basawa-SELCO** [Basawa-SELCO/selco_v2#51]

**Comment by gaurav-naik** [comment]
1. Search for ```File List``` in the Awesome Bar (ERPNext's searchbar)
2. Click on New > Attach the image file as a private file (this will happen by default)
3. Once attached, the path of the file should be /private/files/signature_file.jpg
4. Open the desired print format and edit set the src attribute of the image file in it to /private/files/signature_file.jpg

**Comment by Basawa-SELCO** [comment]
Thanks. its working
