### ISSUE TITLE
Payment entry account selection

### ISSUE THREAD

**Issue by Basawa-SELCO** [Basawa-SELCO/selco_v2#55]
In a new payment entry, the Account has to be selected based on "Money Received By" type. But its not happening.

**Comment by Basawa-SELCO** [comment]
The issue seems to be in the way the Payment Entry Form is Loaded.
Scenario 1:
- Go from "new Payment Entry" 
- It tries to access the Default Account based on the default Money Received BY type which is Cash. In our case the Account is Cash - SELCO.  Since the use doesnt have access to this account , it throws insufficient access error. 
- But the Accounts selection works fine based on type.

Scenario 2:
- Go to Make Payment from Sales Invoice.
- Same issue of lack of permission as it tries to access the default Account.
- Additionally the selection doesnt work. But if we refresh the Payment Entry form, then the selection starts working again.

**Comment by gaurav-naik** [comment]
Can you share which user facing this scenario? Wanted to check roles and permissions

**Comment by Basawa-SELCO** [comment]
Actually all users are facing the issue.
Just now I was checking chikmagalur@selco-india.com..the permission warning is not coming while loading the page but it keeps coming while doing the Money Received By selection. The warning is coming even after giving access to the default accounts which they should not have access to begin with .

**Comment by gaurav-naik** [comment]
A fix had been pushed for this yesterday. Can you confirm if it is working correctly?

**Comment by Basawa-SELCO** [comment]
Yes, seems to be working.
Please explain the fix so that we also understand. The code in the script is still there, so we assume that its not moved to the Python side.

**Comment by gaurav-naik** [comment]
```
frappe.ui.form.on("Payment Entry", "selco_money_received_by", function(frm, cdt, cdn) {
    if (cur_frm.doc.selco_money_received_by == "Cash") {

       //cur_frm.set_value("mode_of_payment", "Cash"); //

        cur_frm.set_value("selco_money_received_by", "Cash");
        cur_frm.set_value("selco_financed", "NO");
        cur_frm.set_value("reference_no", "Cash");
        cur_frm.set_df_property("reference_no", "read_only", true);
...
```
Commented out the line which sets mode of payment in JS. Mode of payment is now being set in selco_payment_entry_validate on py side:
```
def selco_payment_entry_validate(doc,method):
    if doc.payment_type == "Receive":
        if doc.selco_money_received_by == "Cash":
            doc.mode_of_payment = "Cash"
            doc.paid_to = frappe.db.get_value("Branch",doc.selco_branch,"selco_collection_account_cash")
        else:
            doc.mode_of_payment = "Bank"
            doc.paid_to = frappe.db.get_value("Branch",doc.selco_branch,"selco_collection_account")
            
        # if doc.mode_of_payment == "Bank":
        #     doc.paid_to = frappe.db.get_value("Branch",doc.selco_branch,"selco_collection_account")
        # elif doc.mode_of_payment == "Cash":
        #     doc.paid_to = frappe.db.get_value("Branch",doc.selco_branch,"selco_collection_account_cash")
        #     frappe.msgprint("Cash Account is" + doc.paid_to)
    local_sum = 0
    local_sum = doc.paid_amount
    for deduction in doc.deductions:
        local_sum = local_sum + deduction.amount
    doc.received_amount_with_deduction = local_sum
```

**Comment by gaurav-naik** [comment]
```
 if doc.selco_money_received_by == "Cash":
            doc.mode_of_payment = "Cash"
            doc.paid_to = frappe.db.get_value("Branch",doc.selco_branch,"selco_collection_account_cash")
```
Should "selco_collection_account" replace "selco_collection_account_cash" here as well? In line with  #56

**Comment by Basawa-SELCO** [comment]
Yes

**Comment by Basawa-SELCO** [comment]
1) Account Paid from is looking for the default Account "Debtors - SELCO" which the Branch doesnt have permission. So it given insufficient Permission Error.
2) The default  Payment Type is set to Receive and it Read Only. This has to be changed.

**Comment by Basawa-SELCO** [comment]
1. When Money received by is Cash , Its asking for Cheque Reference Date
2. When Money received by is Cheque/DD, Following fields are not getting displayed.

![image](https://user-images.githubusercontent.com/24898695/40960823-821ffbe2-68be-11e8-89ee-b1a3f6ef4e89.png)

3.Paid Amount field (New Field) is getting displayed.
![payment entry](https://user-images.githubusercontent.com/24898695/40961031-0a69e698-68bf-11e8-9067-de49a977575e.png)

**Comment by gaurav-naik** [comment]
Working on this. Will update soon.

**Comment by Basawa-SELCO** [comment]
The new payment entry form still looks for the default account and throws error - Insufficient permission.
The account relevant to this user is already available and it should select this and not look for the default account.

**Comment by gaurav-naik** [comment]
It wasn't doing that yesterday when I checked. Is this still happening for
Kolar@selco-india.com? Or another user?

**Comment by Basawa-SELCO** [comment]
yes, its happening for Kolar also

**Comment by Basawa-SELCO** [comment]
the problem is happening, i mean

**Comment by Basawa-SELCO** [comment]
![image](https://user-images.githubusercontent.com/24898695/41017727-d9576d90-6973-11e8-9acc-2cee1aac85ed.png)

**Comment by Basawa-SELCO** [comment]
![image](https://user-images.githubusercontent.com/24898695/41017752-f3e58cdc-6973-11e8-8ac2-ba34a9cb91b2.png)

**Comment by Basawa-SELCO** [comment]
![image](https://user-images.githubusercontent.com/24898695/41017775-10972412-6974-11e8-9420-a4c13f4595df.png)

**Comment by Basawa-SELCO** [comment]
![image](https://user-images.githubusercontent.com/24898695/41017792-283d5bd6-6974-11e8-8c15-de56f7f12d36.png)

**Comment by Basawa-SELCO** [comment]
When money received by Cheque/DD,

![image](https://user-images.githubusercontent.com/24898695/41017844-7af0a8ec-6974-11e8-8cbf-4a4284e908e9.png)

**Comment by Basawa-SELCO** [comment]
If Payment Type is Pay/Internal Transfer - then 'Money Received By' and Financed By Bank/Microfincnace/NGO' , ''OA NO' and ''ÓA Date' should not be visible

**Comment by Basawa-SELCO** [comment]
For Payment Type as Pay, and when Party Type is Supplier - then in Party Linked field it is showing Customers and not Suppliers

**Comment by gaurav-naik** [comment]
Summing up:
Problems:
- [ ] Insufficient permissions message after selecting Money Received By.
- [x] When payment type is pay Party field shows Customers even if Party Type is Supplier.
- [x] When Money Received By == Cheque/DD, Account Currency is mandatory

New
- [x] If payment type is Internal Transfer/Pay, hide Money Received By, Financed By...", OA NO, OA Date

**Comment by Basawa-SELCO** [comment]
If payment type is Cheque/DD, hide Money Received By, Financed By...", OA NO, OA Date

**Comment by Basawa-SELCO** [comment]
Insufficient Permission:
- We have un-hidden the Account section.
- Then we can set the Account in Customer page. And it works for Payment Entry ( the permission error doesnt come.
- But if we dont set in Customer page ( its tedious) and then choose in Sales Invoice ( where its more logical) we are facing this issue - the Account gets auto selected in Sales Invoice to Debtors - SELCO, though the Branch has no access to this Account.

**Comment by gaurav-naik** [comment]
It will have to be set in Customer. If not, then Sales Invoice will fall back to default behaviour, where it picks up Debtors - SELCO.
