### ISSUE TITLE
code change in payment entry script

### ISSUE THREAD

**Issue by Basawa-SELCO** [Basawa-SELCO/selco_v2#56]
We have updated the code marked below in Payment Entry custom script. The account had to be changed as per the requirement of our Accounts team.
Please ensure that its not overwritten.

frappe.ui.form.on("Payment Entry", "selco_money_received_by", function(frm, cdt, cdn) {
    if (cur_frm.doc.selco_money_received_by == "Cash") {

        cur_frm.set_value("mode_of_payment", "Cash");

        cur_frm.set_value("selco_money_received_by", "Cash");
        cur_frm.set_value("selco_financed", "NO");
        cur_frm.set_value("reference_no", "Cash");
        cur_frm.set_df_property("reference_no", "read_only", true);

        var d = locals[cdt][cdn];
        frappe.call({
        	"method": "frappe.client.get",
        	args: {
        		doctype: "Branch",
        		name: d.selco_branch
        	},
        	callback: function (data) {
        		frappe.model.set_value(d.doctype, d.name, "paid_to", **data.message.selco_collection_account**);
        	}

**Comment by gaurav-naik** [comment]
I have updated the code. Subsequent updates will not affect this.

**Comment by Basawa-SELCO** [comment]
Thanks
