### ISSUE TITLE
configuration change - not to be overwritten

### ISSUE THREAD

**Issue by Basawa-SELCO** [Basawa-SELCO/selco_v2#57]
Please ensure that the following changes are not overwritten:

- We have made Territory as mandatory in Customer DocType.
- Updated the Territory Tree.

**Comment by gaurav-naik** [comment]
If Territory Tree has new data, it will not be affected.
I will make the changes for customer.

**Comment by Basawa-SELCO** [comment]
Can we close this issue?

**Comment by gaurav-naik** [comment]
Yes, please
