### ISSUE TITLE
Workflow In Purchase order

### ISSUE THREAD

**Issue by Basawa-SELCO** [Basawa-SELCO/selco_v2#6]
Workflow In Purchase order not working

**Comment by gaurav-naik** [comment]
Workflow transition rules of v10 have now been aligned with v7. It should work correctly now.

**Comment by Basawa-SELCO** [comment]
Not Fixed. The workflow state option is not coming. Only 'Cancel-PO' Option is coming

**Comment by Basawa-SELCO** [comment]
Fixed
