### ISSUE TITLE
Employee - Customize form - ensure not to overwrite

### ISSUE THREAD

**Issue by Basawa-SELCO** [Basawa-SELCO/selco_v2#61]
Added AAdhaar Number field in Employee DocType

**Comment by gaurav-naik** [comment]
Kindly rename the field to selco_aadhaar_number. Do not want it to conflict with aadhaar_number field if the Frappe team decides to add it as a part of Indian localisations (e.g. GST fields).

**Comment by Basawa-SELCO** [comment]
field has been renamed. has the chnage been pushed?

**Comment by gaurav-naik** [comment]
Yes. This can be closed
