### ISSUE TITLE
Payment Entry - Payment type is Pay

### ISSUE THREAD

**Issue by Basawa-SELCO** [Basawa-SELCO/selco_v2#83]
![supplier_payment](https://user-images.githubusercontent.com/24898695/41454754-3c357116-7098-11e8-8a0a-527602dafa64.png)

**Comment by ghost** [comment]
This has been resolved. Can you please check?

**Comment by Basawa-SELCO** [comment]
Money received by field is still coming for Pay.

**Comment by ghost** [comment]
This has been fixed too.

![pe_payy](https://user-images.githubusercontent.com/29235673/41467129-e601da5c-70c2-11e8-8190-4292f5d0b0d6.gif)

**Comment by Basawa-SELCO** [comment]
Please hide below section also
![financing_institution_for_supplier_payment](https://user-images.githubusercontent.com/24898695/41469746-17381894-70cc-11e8-9cd7-87493d7f461e.png)

**Comment by gaurav-naik** [comment]
- [x] Branch field not visible for shimoga_service_center@selco-india.com
- [x] When type is Pay hide the following:
   - [x] Financed By Bank/Microfinance/NGO, Money Received By
- [x] When type is Pay and Bank/Microfinance/NGO is Yes, make Financing Institution section visible

**Comment by Basawa-SELCO** [comment]
>  When type is Pay and Bank/Microfinance/NGO is Yes, make Financing Institution section visible

This is not a valid case. The actual case is - When type is Pay, Bank/Microfinance/NGO  should be hidden , Financing Institution section should not be visible

**Comment by Basawa-SELCO** [comment]
Any Update?
