### ISSUE TITLE
Material Request - Customize form

### ISSUE THREAD

**Issue by Basawa-SELCO** [Basawa-SELCO/selco_v2#95]
This was fixed before but not working now:
These fields are not getting displayed (Perm Level 2)
DC Number 
DC Date
Godown OA Comments
Logistics Manager Comments
Senior Manager Comments

**Comment by gaurav-naik** [comment]
DC Number, DC Date, Godown OA Comments have Perm level 2 as requested:
https://github.com/Basawa-SELCO/selco_v2/issues/85.

Logistics Manager Comments and Senior Manager Comments have had perm level 3 like before.

No perm-related changes have been made.

Best discussed over screen-share.

**Comment by Basawa-SELCO** [comment]
Thanks. This work as required.
